/**
 * Centralized Emoji Keys Registry for Kuruttina.
 * Dynamically resolved to Discord Developer Portal Application Emojis (<:name:id> / <a:name:id>).
 */
export const EMOJI_KEYS = [
  // Status & Responses
  'SUCCESS',
  'ERROR',
  'WARNING',
  'INFO',
  'LOADING',
  'VERIFIED',
  'DISMISS',
  'OK',

  // Expressions & INFJ Persona
  'OPS',
  'DANCING',
  'KISS',
  'CRY',
  'THINKING',
  'APPEAR',
  'HEHE',
  'ANGER',
  'CLEANING',
  'THUMBUP',
  'PHOTO',
  'SHOOTING',
  'POINTUP',
  'INSPIRED',
  'WAIT',
  'READING',
  'SHRUG',
  'FACEPALM',
  'COFFEE',

  // Command Categories
  'MODERATION',
  'UTILITY',
  'DEVELOPER',
  'ADMIN',
  'FUN',
  'AFFILIATE',
  'STAFF',

  // Actions & Moderation
  'BAN',
  'KICK',
  'MUTE',
  'UNMUTE',
  'CLEAR',
  'SEARCH',
  'ADD',
  'TRASH',
  'SHARE',
  'SHARE_SCREEN',

  // System & Security
  'SHIELD',
  'LOCK',
  'UNLOCK',
  'SETTINGS',
  'LOGS',
  'USER',
  'GUILD',
  'CROWN',

  // UI & Layout Decorations
  'FOLDER',
  'DIAMOND_BLUE',
  'DIAMOND_LARGE',
  'BULLET',
  'HOME',
  'PREV',
  'NEXT',
  'LEFT_ARROW',
  'RIGHT_ARROW',
  'PIN',
  'IDEA',
  'LINE',
  'DIVIDER',

  // Navigation & Branding
  'LINK',
  'DOCUMENTATION',
  'BOOK',
  'STACK_OF_BOOKS',
  'STAR',
] as const;

export type EmojiKey = (typeof EMOJI_KEYS)[number];

/**
 * Default Unicode Emergency Fallback Map.
 */
export const EMOJIS: Record<EmojiKey, string> = {
  SUCCESS: '✅',
  ERROR: '❌',
  WARNING: '⚠️',
  INFO: 'ℹ️',
  LOADING: '⏳',
  VERIFIED: '☑️',
  DISMISS: '🚫',
  OK: '👌',
  OPS: '😳',
  DANCING: '💃',
  KISS: '😘',
  CRY: '😭',
  THINKING: '🤔',
  APPEAR: '✨',
  HEHE: '😏',
  ANGER: '💢',
  CLEANING: '🧹',
  THUMBUP: '👍',
  PHOTO: '🖼️',
  SHOOTING: '💫',
  POINTUP: '☝️',
  INSPIRED: '💡',
  WAIT: '⏳',
  READING: '📖',
  SHRUG: '🤷',
  FACEPALM: '🤦',
  COFFEE: '☕',
  MODERATION: '🛡️',
  UTILITY: '🧰',
  DEVELOPER: '⚙️',
  ADMIN: '👑',
  FUN: '🎉',
  AFFILIATE: '💎',
  STAFF: '👮',
  BAN: '🔨',
  KICK: '🥾',
  MUTE: '🔇',
  UNMUTE: '🔊',
  CLEAR: '🧹',
  SEARCH: '🔍',
  ADD: '➕',
  TRASH: '🗑️',
  SHARE: '📢',
  SHARE_SCREEN: '🖥️',
  SHIELD: '🛡️',
  LOCK: '🔒',
  UNLOCK: '🔓',
  SETTINGS: '⚙️',
  LOGS: '📜',
  USER: '👤',
  GUILD: '🏰',
  CROWN: '👑',
  FOLDER: '📂',
  DIAMOND_BLUE: '🔹',
  DIAMOND_LARGE: '🔷',
  BULLET: '•',
  HOME: '🏠',
  PREV: '◀',
  NEXT: '▶',
  LEFT_ARROW: '⬅️',
  RIGHT_ARROW: '➡️',
  PIN: '📌',
  IDEA: '💡',
  LINE: '➖',
  DIVIDER: '🌸',
  LINK: '🔗',
  DOCUMENTATION: '📚',
  BOOK: '📖',
  STACK_OF_BOOKS: '📚',
  STAR: '⭐',
};

export interface EmojiCategory {
  name: string;
  keys: EmojiKey[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Status & Responses',
    keys: ['SUCCESS', 'ERROR', 'WARNING', 'INFO', 'LOADING', 'VERIFIED', 'DISMISS', 'OK'],
  },
  {
    name: 'Expressions & INFJ Persona',
    keys: [
      'OPS',
      'DANCING',
      'KISS',
      'CRY',
      'THINKING',
      'APPEAR',
      'HEHE',
      'ANGER',
      'CLEANING',
      'THUMBUP',
      'PHOTO',
      'SHOOTING',
      'POINTUP',
      'INSPIRED',
      'WAIT',
      'READING',
      'SHRUG',
      'FACEPALM',
      'COFFEE',
    ],
  },
  {
    name: 'Command Categories',
    keys: ['MODERATION', 'UTILITY', 'DEVELOPER', 'ADMIN', 'FUN', 'AFFILIATE', 'STAFF'],
  },
  {
    name: 'Actions & Moderation',
    keys: ['BAN', 'KICK', 'MUTE', 'UNMUTE', 'CLEAR', 'SEARCH', 'ADD', 'TRASH', 'SHARE', 'SHARE_SCREEN'],
  },
  {
    name: 'System & Security',
    keys: ['SHIELD', 'LOCK', 'UNLOCK', 'SETTINGS', 'LOGS', 'USER', 'GUILD', 'CROWN'],
  },
  {
    name: 'UI & Layout Decorations',
    keys: [
      'FOLDER',
      'DIAMOND_BLUE',
      'DIAMOND_LARGE',
      'BULLET',
      'HOME',
      'PREV',
      'NEXT',
      'LEFT_ARROW',
      'RIGHT_ARROW',
      'PIN',
      'IDEA',
      'LINE',
      'DIVIDER',
    ],
  },
  {
    name: 'Navigation & Branding',
    keys: ['LINK', 'DOCUMENTATION', 'BOOK', 'STACK_OF_BOOKS', 'STAR'],
  },
];
